### ISSUE TITLE
When will the full training dataset be released?

### ISSUE THREAD

**Issue by red-fox-yj** [yuyq18/StepTool#1]

**Comment by yuyq18** [comment]
Thank you for your interest in our work! 

The full training dataset is now available at this [Dropbox link](https://www.dropbox.com/scl/fo/faizqka89m4fbz0ukhwai/AEzVegNkK2sOfvUQQOj2uUQ?rlkey=425kosbbbeihewx61bujnop94&st=62zi4jea&dl=0), and we've also updated the link in the repository's README file for easy access. We appreciate your support and feedback!
