### ISSUE TITLE
Inquiry on Code Release for Step-Grained Reward Assignment

### ISSUE THREAD

**Issue by chenhengzh** [yuyq18/StepTool#2]
Thank you for your exceptional work!

I am particularly interested in the method you used to assign step-grained rewards. Do you have any plans to release the associated code?

**Comment by yuyq18** [comment]
Thank you for your kind words and interest in our work!

In the README document of the repository, we’ve already provided the prompts for using GPT-4 to evaluate 'succeed_tool_calling' and 'contribution_to_final_answer.' After obtaining the annotations, we performed normalization and combined them with equal weights to compute the overall step-grained rewards.

We are in the process of organizing the related code and will make it available as soon as possible. We appreciate your understanding and support.

**Comment by yuyq18** [comment]
We have released the key code for step-grained reward assignment. You can find the details in the following commit: [commit_id: 36435a64d503a15299c2f772d2ad425a7c64d6f4](https://github.com/yuyq18/StepTool/tree/36435a64d503a15299c2f772d2ad425a7c64d6f4). Please let us know if you have any further questions or need additional clarification.
