### ISSUE TITLE
Where does the SFT data in the training dataset come from?

### ISSUE THREAD

**Issue by zhymma** [yuyq18/StepTool#3]
Is the training dataset labeled by GPT-4 or directly sampled from the SFT data of Toolbench? I noticed that their sizes and contents are quite different.

**Comment by yuyq18** [comment]
Thank you for your interest in our project and for pointing this out! 

The SFT data, as mentioned in Section 5.1 "Experimental Settings" under the "Training Setting" paragraph of our paper, comes from expert paths generated by GPT-4. The training tasks were sampled from ToolBench.

Please feel free to reach out if you have further questions or need clarification!
