### ISSUE TITLE
Questions About StepTool Data Generation and Annotation

### ISSUE THREAD

**Issue by chenhengzh** [yuyq18/StepTool#5]
I have a few questions regarding the generation and annotation process for your StepTool data.

### Handling Multi-Branch Structures in DFSDT
When generating expert paths with DFSDT, the resulting data should inherently form a tree structure. Did you process the different branches of the tree explicitly like [ToolPreference](https://arxiv.org/pdf/2406.07115v1), or did you treat it as a single linear chain according to generation order? I’m curious about how you managed the data generation process.  Do you have any plans to release the associated code?

### Reward Assignment for Middle Steps
I noticed that you use a contribution reward to reflect the impact of each middle step on the final outcome. However, it seems the reward assignment does not account for whether the final step ultimately succeeds. This could lead to cases where the rewards for middle steps remain high even if the entire expert path is incorrect, which might not align with the intended goal. Was there a particular reason for doing like this?

**Comment by yuyq18** [comment]
Thank you for your detailed questions and interest in our work! I’m happy to clarify these points.

**1. Handling Multi-Branch Structures in DFSDT:**
We follow the default setting in ToolBench, where the final successful trajectory is used after retries following any failed attempts. While we are aware of the ToolPreference work, which explicitly utilizes the failed and successful branches to construct chosen-rejected pairs for DPO, **our approach does not require this construction**. If a trajectory contains failed attempts, their effects are reflected in our reward assignments for the corresponding steps.


**2. Reward Assignment for Middle Steps:**
The situation you described is precisely one of the motivations behind our step-level RLHF approach. Our perspective is as follows:

First, a successful final result does not necessarily mean that all intermediate steps are optimal; there could still be redundant or erroneous steps in the process. Second, a failed final result does not imply that the intermediate steps are entirely without merit. For example, part of the user query might have been correctly addressed, with only the remaining portion being unsuccessful.

By assigning step-level rewards, our method aims to enhance the quality of intermediate steps with process supervision. 

Thank you again for your thoughtful questions! If you need further clarification or have additional inquiries, feel free to reach out.

**Comment by chenhengzh** [comment]
Thank you for your thoughtful response! 

However, I still have some slight concerns regarding the current approach to reward assignment, particularly in cases where the final result is incorrect. For example, if an incorrect final answer is caused by a particular middle step, evaluating that step based solely on its contribution to the final answer could result in it receiving an undeservedly high reward. In reality, this step is actually a poor one since it directly leads to an incorrect final answer. This approach may not fully reflect its true impact. Perhaps it would be more appropriate to assess the step’s contribution to addressing the task query itself, rather than its influence on the final answer.
