### ISSUE TITLE
script to implement conversion from the reward annotation to step grained for ppo

### ISSUE THREAD

**Issue by yic917** [yuyq18/StepTool#6]
could you please provide scripts which implements the conversion from the reward annotation format to step grained for ppo training samples? Thanks so much!

**Comment by yuyq18** [comment]
The conversion from the reward annotation format to the step-grained format for PPO training samples is relatively straightforward. We believe it can be implemented easily using simple Python code for data extraction and format transformation.

If you encounter any challenges during the process or need clarification on the format details, feel free to reach out, and we'd be happy to assist further.
